stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew build --stacktrace -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew.bat --stop
